### ISSUE TITLE
Add Angular to Bower dependencies

### ISSUE THREAD

**Issue by jayeb** [pusherman/angular-stickyfill#1]
There are many Gulp/Grunt/preprocessor plugins that build a tree using each Bower package's dependencies to determine the proper order of asset loading. Without `angular` specified as a Bower dependency of this plugin, it's possible that this library will be loaded before Angular and result in an error such as:

`angular-stickyfill.js:10 Uncaught TypeError: Cannot read property 'module' of undefined`

**Comment by cwilsn** [comment]
Thanks!
